apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kiali-mcp-server
  name: kiali-mcp-server
  namespace: istio-system
spec:
  ports:
  - name: mcp
    port: 8080
    targetPort: mcp
  selector:
    app.kubernetes.io/name: kiali-mcp-server