# creates service account with permissions to access prometheus metrics
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kiali-mcp-server
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-mcp-server:system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: kiali-mcp-server
    namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-mcp-server
rules:
- apiGroups:
  - "config.openshift.io"
  resources:
  - consoles
  verbs:
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kiali-mcp-server
subjects:
  - kind: ServiceAccount
    name: kiali-mcp-server
    namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali-mcp-server